# GitLab CI configuration
# https://gitlab.com/xn-02f/Proxy-pac.js
image: node:latest

stages:
  - test
  - build

before_script:
  - npm install
  - git submodule init && git submodule update

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run generate
    - npm run dist
