# GitLab CI configuration
# https://gitlab.com/xn-02f/Proxy-pac.js
image: node:latest

stages:
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - npm i

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run generate
    - npm run dist
