sudo: false

language: node_js

node_js:
  - node
  - "8"
  - "6"

before_install:
  - npm install -g gulp-cli

install: npm install

script:
  - npm test
  - gulp

cache:
  directories:
    - node_modules